{
 "title": "Pars bot service monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Среднее за последние 5 минут время затраченное ботом на подключение к веб-сайту и загрузку веб-страницы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(crawler_site_connection_time_sum[5m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Среднее количество обработанных ботом страниц за 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(crawler_pages_parsed[5m])", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Время затраченное ботом на обработку содержимого веб-страницы",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "crawler_page_parse_time_sum", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Время генерации веб-страниц, учитывая время обработки запроса",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "web_page_gen_time_sum", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Количество обработанных запросов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "web_pages_served", "legendFormat": "{{namespace}}" }
   ]
  }
 ]
}