apiVersion: v1
kind: Secret
metadata:
  name: {{ include "externaldns.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}
type: Opaque
data:
  "iamkeyfile.json": {{ .Values.config.auth.json | b64enc }}