---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "externaldns.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ include "externaldns.name" . }}
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include "externaldns.name" . }}-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "externaldns.name" . }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "externaldns.name" . }}
    namespace: {{ .Release.Namespace }}
---